"""
自動レポート生成エンジン

Implements: F-REPORT-001
設計思想:
- HTML/PDF形式のエビデンスレポート
- 実験結果、可視化、設定を自動まとめ
- テンプレートベースで拡張可能
"""

from __future__ import annotations

import base64
import io
import logging
import os
from datetime import datetime
from typing import Any, Dict, List, Optional

import matplotlib.pyplot as plt

logger = logging.getLogger(__name__)


HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }}
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1000px;
            margin: 0 auto;
            padding: 40px 20px;
            background: #f5f5f5;
        }}
        .report {{
            background: white;
            padding: 40px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
            margin-bottom: 30px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
            margin-bottom: 15px;
            padding-left: 10px;
            border-left: 4px solid #3498db;
        }}
        .meta {{
            background: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            font-size: 0.9em;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background: #3498db;
            color: white;
        }}
        tr:hover {{
            background: #f5f5f5;
        }}
        .metric-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }}
        .metric-card {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 10px;
            text-align: center;
        }}
        .metric-value {{
            font-size: 2em;
            font-weight: bold;
        }}
        .metric-name {{
            font-size: 0.9em;
            opacity: 0.9;
        }}
        .figure {{
            margin: 20px 0;
            text-align: center;
        }}
        .figure img {{
            max-width: 100%;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }}
        .figure-caption {{
            font-size: 0.85em;
            color: #666;
            margin-top: 10px;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 0.8em;
            color: #999;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="report">
        <h1>{title}</h1>
        
        <div class="meta">
            <strong>生成日時:</strong> {generated_at}<br>
            <strong>実験名:</strong> {experiment_name}<br>
            <strong>モデル:</strong> {model_type}
        </div>
        
        <h2>📊 評価メトリクス</h2>
        <div class="metric-grid">
            {metrics_html}
        </div>
        
        <h2>⚙️ 設定</h2>
        <table>
            <tr><th>パラメータ</th><th>値</th></tr>
            {config_html}
        </table>
        
        <h2>📈 可視化</h2>
        {figures_html}
        
        <h2>📋 特徴量情報</h2>
        {features_html}
        
        <div class="footer">
            Generated by Chemical ML Platform | {generated_at}
        </div>
    </div>
</body>
</html>
"""


class ReportGenerator:
    """
    実験レポート自動生成エンジン
    
    Features:
    - HTML形式のレポート生成
    - メトリクス、設定、可視化の自動統合
    - PDF変換対応（weasyprintが必要）
    
    Example:
        >>> generator = ReportGenerator()
        >>> html = generator.generate(
        ...     experiment_name="Solubility Prediction",
        ...     metrics={"r2": 0.95, "rmse": 0.15},
        ...     config={"model": "lightgbm", "cv_folds": 5},
        ...     figures=[fig1, fig2],
        ... )
        >>> generator.save_html(html, "report.html")
    """
    
    def __init__(self, output_dir: str = "./reports"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
    
    def generate(
        self,
        experiment_name: str,
        metrics: Dict[str, float],
        config: Dict[str, Any],
        figures: Optional[List[plt.Figure]] = None,
        figure_captions: Optional[List[str]] = None,
        feature_names: Optional[List[str]] = None,
        feature_importances: Optional[Dict[str, float]] = None,
        model_type: str = "Unknown",
    ) -> str:
        """
        HTMLレポートを生成
        
        Args:
            experiment_name: 実験名
            metrics: メトリクス辞書
            config: 設定辞書
            figures: Matplotlibフィギュアリスト
            figure_captions: フィギュアのキャプション
            feature_names: 特徴量名リスト
            feature_importances: 特徴量重要度
            model_type: モデルタイプ
            
        Returns:
            HTML文字列
        """
        # メトリクスHTML
        metrics_html = self._generate_metrics_html(metrics)
        
        # 設定HTML
        config_html = self._generate_config_html(config)
        
        # フィギュアHTML
        figures_html = self._generate_figures_html(figures, figure_captions)
        
        # 特徴量HTML
        features_html = self._generate_features_html(feature_names, feature_importances)
        
        html = HTML_TEMPLATE.format(
            title=f"実験レポート: {experiment_name}",
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            experiment_name=experiment_name,
            model_type=model_type,
            metrics_html=metrics_html,
            config_html=config_html,
            figures_html=figures_html,
            features_html=features_html,
        )
        
        return html
    
    def _generate_metrics_html(self, metrics: Dict[str, float]) -> str:
        """メトリクスカードHTML"""
        cards = []
        for name, value in metrics.items():
            cards.append(f"""
                <div class="metric-card">
                    <div class="metric-value">{value:.4f}</div>
                    <div class="metric-name">{name}</div>
                </div>
            """)
        return "\n".join(cards)
    
    def _generate_config_html(self, config: Dict[str, Any]) -> str:
        """設定テーブルHTML"""
        rows = []
        for key, value in config.items():
            rows.append(f"<tr><td>{key}</td><td>{value}</td></tr>")
        return "\n".join(rows)
    
    def _generate_figures_html(
        self,
        figures: Optional[List[plt.Figure]],
        captions: Optional[List[str]],
    ) -> str:
        """フィギュアHTML"""
        if not figures:
            return "<p>可視化なし</p>"
        
        html_parts = []
        captions = captions or [f"Figure {i+1}" for i in range(len(figures))]
        
        for fig, caption in zip(figures, captions):
            try:
                buf = io.BytesIO()
                fig.savefig(buf, format='png', bbox_inches='tight', dpi=150)
                buf.seek(0)
                img_b64 = base64.b64encode(buf.getvalue()).decode('utf-8')
                
                html_parts.append(f"""
                    <div class="figure">
                        <img src="data:image/png;base64,{img_b64}" alt="{caption}">
                        <div class="figure-caption">{caption}</div>
                    </div>
                """)
            except Exception as e:
                logger.warning(f"Figure conversion failed: {e}")
        
        return "\n".join(html_parts)
    
    def _generate_features_html(
        self,
        feature_names: Optional[List[str]],
        importances: Optional[Dict[str, float]],
    ) -> str:
        """特徴量テーブルHTML"""
        if not feature_names and not importances:
            return "<p>特徴量情報なし</p>"
        
        if importances:
            sorted_imp = sorted(importances.items(), key=lambda x: x[1], reverse=True)[:20]
            rows = [
                f"<tr><td>{name}</td><td>{imp:.4f}</td></tr>"
                for name, imp in sorted_imp
            ]
            return f"""
                <table>
                    <tr><th>特徴量</th><th>重要度</th></tr>
                    {"".join(rows)}
                </table>
            """
        
        if feature_names:
            return f"<p>使用特徴量: {len(feature_names)}件</p><p>{', '.join(feature_names[:20])}...</p>"
        
        return ""
    
    def save_html(self, html: str, filename: str) -> str:
        """HTMLを保存"""
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)
        logger.info(f"Report saved: {filepath}")
        return filepath
    
    def save_pdf(self, html: str, filename: str) -> Optional[str]:
        """PDFを保存（weasyprint必要）"""
        try:
            from weasyprint import HTML
            
            filepath = os.path.join(self.output_dir, filename)
            HTML(string=html).write_pdf(filepath)
            logger.info(f"PDF saved: {filepath}")
            return filepath
            
        except ImportError:
            logger.warning("weasyprint required for PDF. Run: pip install weasyprint")
            return None
